---
apiVersion: v1
kind: Service
metadata:
  namespace: vpn
  name: ipsec-vpn-server-aws-nlb
  annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '9100'
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=prod,job=ipsec-vpn-server"
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "false"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb 
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "180"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "5"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
        service.kubernetes.io/local-svc-only-bind-node-with-pod: "true"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stikiness.enabled=true
        service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: persevere_client_ip.enabled=true
  labels:
    app: ipsec-vpn-server
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local 
  ports:
  - name: vpnisakmp
    port: 500
    targetPort: 500
    protocol: UDP
  - name: vpnike
    port: 4500
    targetPort: 4500
    protocol: UDP   
  selector:
    app: ipsec-vpn-server
