---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipsec-config-secret
  namespace: vpn
data:
  ipsec.secrets: |
          # Specify the PSK here not in pod environment (for this test I used:  "head -c 30 /dev/random | base64" )
          %any  %any  : PSK "lutDg2Jnb3jIeGn8NM9IggY5hFLyG/n0d6sXClLm"

